[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "python --version",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

