[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python --version",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

